### ISSUE TITLE
JsonExtractor only supports 10 fields

### ISSUE THREAD

**Issue by jlashmet** [oci-pronghorn/PronghornPipes#53]
Hi,

First off, just wanted to say awesome project!  I've been playing around with it for a few weeks and the performance is amazing.  The main problems I've been running into are related to large payloads.  Increasing the size of some pipes was easy enough, but I can't figure out why I get an exception when adding more than 10 fields to a JsonExtractor.  When adding the 11th field, I get the following exception:

java.lang.UnsupportedOperationException: field 1 conflicts with previous field, each must be unique.
	at com.ociweb.pronghorn.util.parse.JSONFieldMapping.addHashToTable(JSONFieldMapping.java:161)
	at com.ociweb.pronghorn.util.parse.JSONStreamVisitorToChannel.<init>(JSONStreamVisitorToChannel.java:212)
	at com.ociweb.json.JSONExtractorImpl.newJSONVisitor(JSONExtractorImpl.java:104)
	at com.ociweb.json.decode.JSONExtractor.newJSONVisitor(JSONExtractor.java:43)
	at com.ociweb.json.parse.JSONParseTest.parseJSON(JSONParseTest.java:493)
	at com.ociweb.json.parse.JSONParseTest.largeFieldCountParseTest(JSONParseTest.java:643)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

Thanks,
Jason

**Comment by jlashmet** [comment]
Here's a test that reproduces the issue...

[JSONParseTest.txt](https://github.com/oci-pronghorn/PronghornPipes/files/2058350/JSONParseTest.txt)
